version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: chinook
      MYSQL_PASSWORD: chinook
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Chinook
    ports:
      - "3309:3306"
    volumes:
      - ./chinook-database\ChinookDatabase\DataSources\Chinook_MySql.sql:/docker-entrypoint-initdb.d/Chinook_MySql.sql
      - ./chinook-database\ChinookDatabase\DataSources\Chinook_MySql_AutoIncrementPKs.sql:/docker-entrypoint-initdb.d/Chinook_MySql_AutoIncrementPKs.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:

# Conectarse a la base de datos
# mysql -u root -h localhost -P 3306 -p

# modificar permisos de usuarios
# ALTER USER 'root'@'%' IDENTIFIED BY 'root';